### ISSUE TITLE
OpenEMM 19/20: Generating online archive throws error

### ISSUE THREAD

**Issue by svewap** [agnitas-org/openemm#13]
Hi,
I'm trying to generate the online archive for mailings. I used the manual to create the action and form.
If I call the form with https://<url>/form.do?agnCI=1&agnFN=archive_overview OpenEMM goes into the error state. I tried it first with OpenEMM 19, then i updated to 20, but the problem still exists. Since no more precise error code is output (in emm_error.log file), unfortunately no approach for a solution can be found.

`2020-06-10 13:05:16,251: ERROR [http-nio-8080-exec-20] com.agnitas.userform.bean.impl.UserFormImpl - Action Error: CompanyID=1, ActionID=8, error codes=[]`

Could the error output be improved?

Thanks, Sven

**Comment by agnitas-org** [comment]
Please use the OpenEMM forums at https://forum.openemm.org/ for feedback.
