### ISSUE TITLE
20.10- mailinglists/mailinglist-users-view.jsp not found when clicking "Manage approval"

### ISSUE THREAD

**Issue by se1by** [agnitas-org/openemm#16]
System: CentOS 8
OpenEMM version: 20.10.000.107

When you click the "Manage approval" button on a mailing list, you get a 500 error with the following stacktrace:

> 2020-12-17 09:32:00,239: ERROR [http-nio-8080-exec-4] org.apache.struts.tiles.taglib.InsertTag - ServletException in '/WEB-INF/jsp/mailinglists/mailinglist-users-view.jsp': File [/WEB-INF/jsp/mailinglists/mailinglist-users-view.jsp] not found
> javax.servlet.ServletException: File [/WEB-INF/jsp/mailinglists/mailinglist-users-view.jsp] not found
> 	at org.apache.jasper.servlet.JspServlet.handleMissingResource(JspServlet.java:407)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:374)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
> 	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580)
> 	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516)
> 	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955)
> 	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:490)
> 	at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:138)
> 	at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:152)
> 	at org.apache.struts.tiles.taglib.InsertTag.doInclude(InsertTag.java:764)
> 	at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:896)
> 	at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)
> 	at org.apache.jsp.WEB_002dINF.jsp.ajax_002dresponse_002dtemplate_jsp._jspx_meth_tiles_005finsert_005f1(ajax_002dresponse_002dtemplate_jsp.java:197)
> 	at org.apache.jsp.WEB_002dINF.jsp.ajax_002dresponse_002dtemplate_jsp._jspService(ajax_002dresponse_002dtemplate_jsp.java:134)
> 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
> 	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
> 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:304)
> 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
> 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.agnitas.emm.core.commons.filter.OriginUriFilter.doFilter(OriginUriFilter.java:43)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.agnitas.emm.core.commons.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:80)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.agnitas.emm.core.sessionhijacking.web.GroupingSessionHijackingPreventionFilter.doFilter(GroupingSessionHijackingPreventionFilter.java:105)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.agnitas.web.filter.HttpSecurityHeaderFilter.doFilter(HttpSecurityHeaderFilter.java:108)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.agnitas.emm.core.commons.filter.LoadBalancerFilter.doFilter(LoadBalancerFilter.java:153)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by agnitas-org** [comment]
assigned bug ticket: O-498

**Comment by agnitas-org** [comment]
Fixed
