### ISSUE TITLE
Double-Opt-In for multiple mailing lists

### ISSUE THREAD

**Issue by binarious** [agnitas-org/openemm#7]
More a question, but since the forum and website aren't available I'm going to post it here:
As per documentation an action-based mailing needs to be created for a double-opt-in mail. The target mailing list needs to be selected in this action-based mailing. How would one create a global double-opt-in email for all mailings? We have over 20 mailing lists. Do we need to create 20 action-based mailings? And how would we choose the right action depending on the chosen mailing lists in the registration form?

**Comment by agnitas-org** [comment]
Please use the support forum at https://forum.openemm.org .
